# Generated by Django 3.0 on 2020-01-04 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zespol', '0008_auto_20200104_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='nazwisko',
        ),
    ]
