# Generated by Django 3.0 on 2020-01-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zespol', '0009_auto_20200104_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imie',
            field=models.CharField(max_length=30, verbose_name='imie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nazwisko',
            field=models.CharField(max_length=30, verbose_name='nazwisko'),
        ),
    ]
